osx_image: xcode7
language: objective-c
cache:
  - bundler
  - cocoapods
install:
  - "bundle install"
  - "travis_wait bundle exec pod install"
before_script:
  - set -o pipefail
script:
  - xcodebuild -workspace MacDown.xcworkspace -scheme MacDown test | xcpretty
